/* parasoft-begin-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names, DRV-4756" */
/* parasoft-begin-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names, DRV-4756" */

/******************************************************************************
*
* (C) 2023 Cadence Design Systems, Inc. 
*
******************************************************************************
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its
*    contributors may be used to endorse or promote products derived from
*    this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
******************************************************************************
*

 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_SD4HC_HRS_MACROS_H_
#define REG_SD4HC_HRS_MACROS_H_

#define SD4HC__HRS__HRS00_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS00_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS00_WOSET_MASK                                 0x00000001U
#define SD4HC__HRS__HRS00__SWR_MASK                                  0x00000001U
#define SD4HC__HRS__HRS00__SWR_SHIFT                                          0U
#define SD4HC__HRS__HRS00__SWR_WIDTH                                          1U
#define SD4HC__HRS__HRS00__SWR_WOCLR                                          0U
#define SD4HC__HRS__HRS00__SWR_WOSET                                          1U
#define SD4HC__HRS__HRS00__RSVD_0_MASK                               0x0000FFFEU
#define SD4HC__HRS__HRS00__RSVD_0_SHIFT                                       1U
#define SD4HC__HRS__HRS00__RSVD_0_WIDTH                                      15U
#define SD4HC__HRS__HRS00__SAV_MASK                                  0x00FF0000U
#define SD4HC__HRS__HRS00__SAV_SHIFT                                         16U
#define SD4HC__HRS__HRS00__SAV_WIDTH                                          8U
#define SD4HC__HRS__HRS00__RSVD_1_MASK                               0xFF000000U
#define SD4HC__HRS__HRS00__RSVD_1_SHIFT                                      24U
#define SD4HC__HRS__HRS00__RSVD_1_WIDTH                                       8U

#define SD4HC__HRS__HRS01_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS01_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS01__DP_MASK                                   0x00FFFFFFU
#define SD4HC__HRS__HRS01__DP_SHIFT                                           0U
#define SD4HC__HRS__HRS01__DP_WIDTH                                          24U
#define SD4HC__HRS__HRS01__RSVD_0_MASK                               0xFF000000U
#define SD4HC__HRS__HRS01__RSVD_0_SHIFT                                      24U
#define SD4HC__HRS__HRS01__RSVD_0_WIDTH                                       8U

#define SD4HC__HRS__HRS02_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS02_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS02__PBL_MASK                                  0x0000000FU
#define SD4HC__HRS__HRS02__PBL_SHIFT                                          0U
#define SD4HC__HRS__HRS02__PBL_WIDTH                                          4U
#define SD4HC__HRS__HRS02__RSVD_0_MASK                               0x0000FFF0U
#define SD4HC__HRS__HRS02__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS02__RSVD_0_WIDTH                                      12U
#define SD4HC__HRS__HRS02__OTN_MASK                                  0x00030000U
#define SD4HC__HRS__HRS02__OTN_SHIFT                                         16U
#define SD4HC__HRS__HRS02__OTN_WIDTH                                          2U
#define SD4HC__HRS__HRS02__RSVD_1_MASK                               0xFFFC0000U
#define SD4HC__HRS__HRS02__RSVD_1_SHIFT                                      18U
#define SD4HC__HRS__HRS02__RSVD_1_WIDTH                                      14U

#define SD4HC__HRS__HRS03_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS03_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS03_WOCLR_MASK                                 0x0000000FU
#define SD4HC__HRS__HRS03__AER_RD_MASK                               0x00000001U
#define SD4HC__HRS__HRS03__AER_RD_SHIFT                                       0U
#define SD4HC__HRS__HRS03__AER_RD_WIDTH                                       1U
#define SD4HC__HRS__HRS03__AER_RD_WOCLR                                       1U
#define SD4HC__HRS__HRS03__AER_RD_WOSET                                       0U
#define SD4HC__HRS__HRS03__AER_RS_MASK                               0x00000002U
#define SD4HC__HRS__HRS03__AER_RS_SHIFT                                       1U
#define SD4HC__HRS__HRS03__AER_RS_WIDTH                                       1U
#define SD4HC__HRS__HRS03__AER_RS_WOCLR                                       1U
#define SD4HC__HRS__HRS03__AER_RS_WOSET                                       0U
#define SD4HC__HRS__HRS03__AER_BD_MASK                               0x00000004U
#define SD4HC__HRS__HRS03__AER_BD_SHIFT                                       2U
#define SD4HC__HRS__HRS03__AER_BD_WIDTH                                       1U
#define SD4HC__HRS__HRS03__AER_BD_WOCLR                                       1U
#define SD4HC__HRS__HRS03__AER_BD_WOSET                                       0U
#define SD4HC__HRS__HRS03__AER_BS_MASK                               0x00000008U
#define SD4HC__HRS__HRS03__AER_BS_SHIFT                                       3U
#define SD4HC__HRS__HRS03__AER_BS_WIDTH                                       1U
#define SD4HC__HRS__HRS03__AER_BS_WOCLR                                       1U
#define SD4HC__HRS__HRS03__AER_BS_WOSET                                       0U
#define SD4HC__HRS__HRS03__RSVD_0_MASK                               0x000000F0U
#define SD4HC__HRS__HRS03__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS03__RSVD_0_WIDTH                                       4U
#define SD4HC__HRS__HRS03__AER_SENRD_MASK                            0x00000100U
#define SD4HC__HRS__HRS03__AER_SENRD_SHIFT                                    8U
#define SD4HC__HRS__HRS03__AER_SENRD_WIDTH                                    1U
#define SD4HC__HRS__HRS03__AER_SENRD_WOCLR                                    0U
#define SD4HC__HRS__HRS03__AER_SENRD_WOSET                                    0U
#define SD4HC__HRS__HRS03__AER_SENRS_MASK                            0x00000200U
#define SD4HC__HRS__HRS03__AER_SENRS_SHIFT                                    9U
#define SD4HC__HRS__HRS03__AER_SENRS_WIDTH                                    1U
#define SD4HC__HRS__HRS03__AER_SENRS_WOCLR                                    0U
#define SD4HC__HRS__HRS03__AER_SENRS_WOSET                                    0U
#define SD4HC__HRS__HRS03__AER_SENBD_MASK                            0x00000400U
#define SD4HC__HRS__HRS03__AER_SENBD_SHIFT                                   10U
#define SD4HC__HRS__HRS03__AER_SENBD_WIDTH                                    1U
#define SD4HC__HRS__HRS03__AER_SENBD_WOCLR                                    0U
#define SD4HC__HRS__HRS03__AER_SENBD_WOSET                                    0U
#define SD4HC__HRS__HRS03__AER_SENBS_MASK                            0x00000800U
#define SD4HC__HRS__HRS03__AER_SENBS_SHIFT                                   11U
#define SD4HC__HRS__HRS03__AER_SENBS_WIDTH                                    1U
#define SD4HC__HRS__HRS03__AER_SENBS_WOCLR                                    0U
#define SD4HC__HRS__HRS03__AER_SENBS_WOSET                                    0U
#define SD4HC__HRS__HRS03__RSVD_1_MASK                               0x0000F000U
#define SD4HC__HRS__HRS03__RSVD_1_SHIFT                                      12U
#define SD4HC__HRS__HRS03__RSVD_1_WIDTH                                       4U
#define SD4HC__HRS__HRS03__AER_IERD_MASK                             0x00010000U
#define SD4HC__HRS__HRS03__AER_IERD_SHIFT                                    16U
#define SD4HC__HRS__HRS03__AER_IERD_WIDTH                                     1U
#define SD4HC__HRS__HRS03__AER_IERD_WOCLR                                     0U
#define SD4HC__HRS__HRS03__AER_IERD_WOSET                                     0U
#define SD4HC__HRS__HRS03__AER_IERS_MASK                             0x00020000U
#define SD4HC__HRS__HRS03__AER_IERS_SHIFT                                    17U
#define SD4HC__HRS__HRS03__AER_IERS_WIDTH                                     1U
#define SD4HC__HRS__HRS03__AER_IERS_WOCLR                                     0U
#define SD4HC__HRS__HRS03__AER_IERS_WOSET                                     0U
#define SD4HC__HRS__HRS03__AER_IEBD_MASK                             0x00040000U
#define SD4HC__HRS__HRS03__AER_IEBD_SHIFT                                    18U
#define SD4HC__HRS__HRS03__AER_IEBD_WIDTH                                     1U
#define SD4HC__HRS__HRS03__AER_IEBD_WOCLR                                     0U
#define SD4HC__HRS__HRS03__AER_IEBD_WOSET                                     0U
#define SD4HC__HRS__HRS03__AER_IEBS_MASK                             0x00080000U
#define SD4HC__HRS__HRS03__AER_IEBS_SHIFT                                    19U
#define SD4HC__HRS__HRS03__AER_IEBS_WIDTH                                     1U
#define SD4HC__HRS__HRS03__AER_IEBS_WOCLR                                     0U
#define SD4HC__HRS__HRS03__AER_IEBS_WOSET                                     0U
#define SD4HC__HRS__HRS03__RSVD_2_MASK                               0xFFF00000U
#define SD4HC__HRS__HRS03__RSVD_2_SHIFT                                      20U
#define SD4HC__HRS__HRS03__RSVD_2_WIDTH                                      12U

#define SD4HC__HRS__HRS04_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS04_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS04__PHYREGADDR_MASK                           0x0000FFFFU
#define SD4HC__HRS__HRS04__PHYREGADDR_SHIFT                                   0U
#define SD4HC__HRS__HRS04__PHYREGADDR_WIDTH                                  16U
#define SD4HC__HRS__HRS04__RSVD_0_MASK                               0xFFFF0000U
#define SD4HC__HRS__HRS04__RSVD_0_SHIFT                                      16U
#define SD4HC__HRS__HRS04__RSVD_0_WIDTH                                      16U

#define SD4HC__HRS__HRS05_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS05_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS05__PHYREGDATA_MASK                           0xFFFFFFFFU
#define SD4HC__HRS__HRS05__PHYREGDATA_SHIFT                                   0U
#define SD4HC__HRS__HRS05__PHYREGDATA_WIDTH                                  32U

#define SD4HC__HRS__HRS06_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS06_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS06__EMM_MASK                                  0x00000007U
#define SD4HC__HRS__HRS06__EMM_SHIFT                                          0U
#define SD4HC__HRS__HRS06__EMM_WIDTH                                          3U
#define SD4HC__HRS__HRS06__RSVD_0_MASK                               0xFFFFFFF8U
#define SD4HC__HRS__HRS06__RSVD_0_SHIFT                                       3U
#define SD4HC__HRS__HRS06__RSVD_0_WIDTH                                      29U

#define SD4HC__HRS__HRS07_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS07_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS07__IDELAY_VAL_MASK                           0x0000001FU
#define SD4HC__HRS__HRS07__IDELAY_VAL_SHIFT                                   0U
#define SD4HC__HRS__HRS07__IDELAY_VAL_WIDTH                                   5U
#define SD4HC__HRS__HRS07__RSVD_0_MASK                               0x0000FFE0U
#define SD4HC__HRS__HRS07__RSVD_0_SHIFT                                       5U
#define SD4HC__HRS__HRS07__RSVD_0_WIDTH                                      11U
#define SD4HC__HRS__HRS07__RW_COMPENSATE_MASK                        0x001F0000U
#define SD4HC__HRS__HRS07__RW_COMPENSATE_SHIFT                               16U
#define SD4HC__HRS__HRS07__RW_COMPENSATE_WIDTH                                5U
#define SD4HC__HRS__HRS07__RSVD_1_MASK                               0xFFE00000U
#define SD4HC__HRS__HRS07__RSVD_1_SHIFT                                      21U
#define SD4HC__HRS__HRS07__RSVD_1_WIDTH                                      11U

#define SD4HC__HRS__HRS08_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS08_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS08__PHY_DLL_UPDREQ_MASK                       0x00000001U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDREQ_SHIFT                               0U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDREQ_WIDTH                               1U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDREQ_WOCLR                               0U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDREQ_WOSET                               0U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDACK_MASK                       0x00000002U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDACK_SHIFT                               1U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDACK_WIDTH                               1U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDACK_WOCLR                               0U
#define SD4HC__HRS__HRS08__PHY_DLL_UPDACK_WOSET                               0U
#define SD4HC__HRS__HRS08__RSVD_0_MASK                               0xFFFFFFFCU
#define SD4HC__HRS__HRS08__RSVD_0_SHIFT                                       2U
#define SD4HC__HRS__HRS08__RSVD_0_WIDTH                                      30U

#define SD4HC__HRS__HRS09_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS09_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS09__PHY_SW_RESET_MASK                         0x00000001U
#define SD4HC__HRS__HRS09__PHY_SW_RESET_SHIFT                                 0U
#define SD4HC__HRS__HRS09__PHY_SW_RESET_WIDTH                                 1U
#define SD4HC__HRS__HRS09__PHY_SW_RESET_WOCLR                                 0U
#define SD4HC__HRS__HRS09__PHY_SW_RESET_WOSET                                 0U
#define SD4HC__HRS__HRS09__PHY_INIT_COMPLETE_MASK                    0x00000002U
#define SD4HC__HRS__HRS09__PHY_INIT_COMPLETE_SHIFT                            1U
#define SD4HC__HRS__HRS09__PHY_INIT_COMPLETE_WIDTH                            1U
#define SD4HC__HRS__HRS09__PHY_INIT_COMPLETE_WOCLR                            0U
#define SD4HC__HRS__HRS09__PHY_INIT_COMPLETE_WOSET                            0U
#define SD4HC__HRS__HRS09__EXTENDED_RD_MODE_MASK                     0x00000004U
#define SD4HC__HRS__HRS09__EXTENDED_RD_MODE_SHIFT                             2U
#define SD4HC__HRS__HRS09__EXTENDED_RD_MODE_WIDTH                             1U
#define SD4HC__HRS__HRS09__EXTENDED_RD_MODE_WOCLR                             0U
#define SD4HC__HRS__HRS09__EXTENDED_RD_MODE_WOSET                             0U
#define SD4HC__HRS__HRS09__EXTENDED_WR_MODE_MASK                     0x00000008U
#define SD4HC__HRS__HRS09__EXTENDED_WR_MODE_SHIFT                             3U
#define SD4HC__HRS__HRS09__EXTENDED_WR_MODE_WIDTH                             1U
#define SD4HC__HRS__HRS09__EXTENDED_WR_MODE_WOCLR                             0U
#define SD4HC__HRS__HRS09__EXTENDED_WR_MODE_WOSET                             0U
#define SD4HC__HRS__HRS09__RSVD_0_MASK                               0x00007FF0U
#define SD4HC__HRS__HRS09__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS09__RSVD_0_WIDTH                                      11U
#define SD4HC__HRS__HRS09__RDCMD_EN_MASK                             0x00008000U
#define SD4HC__HRS__HRS09__RDCMD_EN_SHIFT                                    15U
#define SD4HC__HRS__HRS09__RDCMD_EN_WIDTH                                     1U
#define SD4HC__HRS__HRS09__RDCMD_EN_WOCLR                                     0U
#define SD4HC__HRS__HRS09__RDCMD_EN_WOSET                                     0U
#define SD4HC__HRS__HRS09__RDDATA_EN_MASK                            0x00010000U
#define SD4HC__HRS__HRS09__RDDATA_EN_SHIFT                                   16U
#define SD4HC__HRS__HRS09__RDDATA_EN_WIDTH                                    1U
#define SD4HC__HRS__HRS09__RDDATA_EN_WOCLR                                    0U
#define SD4HC__HRS__HRS09__RDDATA_EN_WOSET                                    0U
#define SD4HC__HRS__HRS09__RSVD_1_MASK                               0x003E0000U
#define SD4HC__HRS__HRS09__RSVD_1_SHIFT                                      17U
#define SD4HC__HRS__HRS09__RSVD_1_WIDTH                                       5U
#define SD4HC__HRS__HRS09__LVSI_TCKSEL_MASK                          0x0FC00000U
#define SD4HC__HRS__HRS09__LVSI_TCKSEL_SHIFT                                 22U
#define SD4HC__HRS__HRS09__LVSI_TCKSEL_WIDTH                                  6U
#define SD4HC__HRS__HRS09__LVSI_CNT_MASK                             0xF0000000U
#define SD4HC__HRS__HRS09__LVSI_CNT_SHIFT                                    28U
#define SD4HC__HRS__HRS09__LVSI_CNT_WIDTH                                     4U

#define SD4HC__HRS__HRS10_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS10_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS10__RSVD_0_MASK                               0x0000FFFFU
#define SD4HC__HRS__HRS10__RSVD_0_SHIFT                                       0U
#define SD4HC__HRS__HRS10__RSVD_0_WIDTH                                      16U
#define SD4HC__HRS__HRS10__HCSDCLKADJ_MASK                           0x000F0000U
#define SD4HC__HRS__HRS10__HCSDCLKADJ_SHIFT                                  16U
#define SD4HC__HRS__HRS10__HCSDCLKADJ_WIDTH                                   4U
#define SD4HC__HRS__HRS10__RSVD_1_MASK                               0x00300000U
#define SD4HC__HRS__HRS10__RSVD_1_SHIFT                                      20U
#define SD4HC__HRS__HRS10__RSVD_1_WIDTH                                       2U
#define SD4HC__HRS__HRS10__RDDATA_SWAP_MASK                          0x00400000U
#define SD4HC__HRS__HRS10__RDDATA_SWAP_SHIFT                                 22U
#define SD4HC__HRS__HRS10__RDDATA_SWAP_WIDTH                                  1U
#define SD4HC__HRS__HRS10__RDDATA_SWAP_WOCLR                                  0U
#define SD4HC__HRS__HRS10__RDDATA_SWAP_WOSET                                  0U
#define SD4HC__HRS__HRS10__RSVD_2_MASK                               0xFF800000U
#define SD4HC__HRS__HRS10__RSVD_2_SHIFT                                      23U
#define SD4HC__HRS__HRS10__RSVD_2_WIDTH                                       9U

#define SD4HC__HRS__HRS11_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS11_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS11__EMMC_RST_MASK                             0x00000001U
#define SD4HC__HRS__HRS11__EMMC_RST_SHIFT                                     0U
#define SD4HC__HRS__HRS11__EMMC_RST_WIDTH                                     1U
#define SD4HC__HRS__HRS11__EMMC_RST_WOCLR                                     0U
#define SD4HC__HRS__HRS11__EMMC_RST_WOSET                                     0U
#define SD4HC__HRS__HRS11__RSVD_0_MASK                               0xFFFFFFFEU
#define SD4HC__HRS__HRS11__RSVD_0_SHIFT                                       1U
#define SD4HC__HRS__HRS11__RSVD_0_WIDTH                                      31U

#define SD4HC__HRS__HRS12_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS12_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS12_WOCLR_MASK                                 0x0000000FU
#define SD4HC__HRS__HRS12__PHYCMDUR_MASK                             0x00000001U
#define SD4HC__HRS__HRS12__PHYCMDUR_SHIFT                                     0U
#define SD4HC__HRS__HRS12__PHYCMDUR_WIDTH                                     1U
#define SD4HC__HRS__HRS12__PHYCMDUR_WOCLR                                     1U
#define SD4HC__HRS__HRS12__PHYCMDUR_WOSET                                     0U
#define SD4HC__HRS__HRS12__PHYCMDOF_MASK                             0x00000002U
#define SD4HC__HRS__HRS12__PHYCMDOF_SHIFT                                     1U
#define SD4HC__HRS__HRS12__PHYCMDOF_WIDTH                                     1U
#define SD4HC__HRS__HRS12__PHYCMDOF_WOCLR                                     1U
#define SD4HC__HRS__HRS12__PHYCMDOF_WOSET                                     0U
#define SD4HC__HRS__HRS12__PHYDATUR_MASK                             0x00000004U
#define SD4HC__HRS__HRS12__PHYDATUR_SHIFT                                     2U
#define SD4HC__HRS__HRS12__PHYDATUR_WIDTH                                     1U
#define SD4HC__HRS__HRS12__PHYDATUR_WOCLR                                     1U
#define SD4HC__HRS__HRS12__PHYDATUR_WOSET                                     0U
#define SD4HC__HRS__HRS12__PHYDATOF_MASK                             0x00000008U
#define SD4HC__HRS__HRS12__PHYDATOF_SHIFT                                     3U
#define SD4HC__HRS__HRS12__PHYDATOF_WIDTH                                     1U
#define SD4HC__HRS__HRS12__PHYDATOF_WOCLR                                     1U
#define SD4HC__HRS__HRS12__PHYDATOF_WOSET                                     0U
#define SD4HC__HRS__HRS12__RSVD_0_MASK                               0xFFFFFFF0U
#define SD4HC__HRS__HRS12__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS12__RSVD_0_WIDTH                                      28U

#define SD4HC__HRS__HRS13_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS13_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS13__PHYCMDUR_SE_MASK                          0x00000001U
#define SD4HC__HRS__HRS13__PHYCMDUR_SE_SHIFT                                  0U
#define SD4HC__HRS__HRS13__PHYCMDUR_SE_WIDTH                                  1U
#define SD4HC__HRS__HRS13__PHYCMDUR_SE_WOCLR                                  0U
#define SD4HC__HRS__HRS13__PHYCMDUR_SE_WOSET                                  0U
#define SD4HC__HRS__HRS13__PHYCMDOF_SE_MASK                          0x00000002U
#define SD4HC__HRS__HRS13__PHYCMDOF_SE_SHIFT                                  1U
#define SD4HC__HRS__HRS13__PHYCMDOF_SE_WIDTH                                  1U
#define SD4HC__HRS__HRS13__PHYCMDOF_SE_WOCLR                                  0U
#define SD4HC__HRS__HRS13__PHYCMDOF_SE_WOSET                                  0U
#define SD4HC__HRS__HRS13__PHYDATUR_SE_MASK                          0x00000004U
#define SD4HC__HRS__HRS13__PHYDATUR_SE_SHIFT                                  2U
#define SD4HC__HRS__HRS13__PHYDATUR_SE_WIDTH                                  1U
#define SD4HC__HRS__HRS13__PHYDATUR_SE_WOCLR                                  0U
#define SD4HC__HRS__HRS13__PHYDATUR_SE_WOSET                                  0U
#define SD4HC__HRS__HRS13__PHYDATOF_SE_MASK                          0x00000008U
#define SD4HC__HRS__HRS13__PHYDATOF_SE_SHIFT                                  3U
#define SD4HC__HRS__HRS13__PHYDATOF_SE_WIDTH                                  1U
#define SD4HC__HRS__HRS13__PHYDATOF_SE_WOCLR                                  0U
#define SD4HC__HRS__HRS13__PHYDATOF_SE_WOSET                                  0U
#define SD4HC__HRS__HRS13__RSVD_0_MASK                               0xFFFFFFF0U
#define SD4HC__HRS__HRS13__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS13__RSVD_0_WIDTH                                      28U

#define SD4HC__HRS__HRS14_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS14_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS14__PHYCMDUR_IE_MASK                          0x00000001U
#define SD4HC__HRS__HRS14__PHYCMDUR_IE_SHIFT                                  0U
#define SD4HC__HRS__HRS14__PHYCMDUR_IE_WIDTH                                  1U
#define SD4HC__HRS__HRS14__PHYCMDUR_IE_WOCLR                                  0U
#define SD4HC__HRS__HRS14__PHYCMDUR_IE_WOSET                                  0U
#define SD4HC__HRS__HRS14__PHYCMDOF_IE_MASK                          0x00000002U
#define SD4HC__HRS__HRS14__PHYCMDOF_IE_SHIFT                                  1U
#define SD4HC__HRS__HRS14__PHYCMDOF_IE_WIDTH                                  1U
#define SD4HC__HRS__HRS14__PHYCMDOF_IE_WOCLR                                  0U
#define SD4HC__HRS__HRS14__PHYCMDOF_IE_WOSET                                  0U
#define SD4HC__HRS__HRS14__PHYDATUR_IE_MASK                          0x00000004U
#define SD4HC__HRS__HRS14__PHYDATUR_IE_SHIFT                                  2U
#define SD4HC__HRS__HRS14__PHYDATUR_IE_WIDTH                                  1U
#define SD4HC__HRS__HRS14__PHYDATUR_IE_WOCLR                                  0U
#define SD4HC__HRS__HRS14__PHYDATUR_IE_WOSET                                  0U
#define SD4HC__HRS__HRS14__PHYDATOF_IE_MASK                          0x00000008U
#define SD4HC__HRS__HRS14__PHYDATOF_IE_SHIFT                                  3U
#define SD4HC__HRS__HRS14__PHYDATOF_IE_WIDTH                                  1U
#define SD4HC__HRS__HRS14__PHYDATOF_IE_WOCLR                                  0U
#define SD4HC__HRS__HRS14__PHYDATOF_IE_WOSET                                  0U
#define SD4HC__HRS__HRS14__RSVD_0_MASK                               0xFFFFFFF0U
#define SD4HC__HRS__HRS14__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS14__RSVD_0_WIDTH                                      28U

#define SD4HC__HRS__HRS16_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS16_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS16__WRCMD0_DLY_MASK                           0x0000000FU
#define SD4HC__HRS__HRS16__WRCMD0_DLY_SHIFT                                   0U
#define SD4HC__HRS__HRS16__WRCMD0_DLY_WIDTH                                   4U
#define SD4HC__HRS__HRS16__WRCMD1_DLY_MASK                           0x000000F0U
#define SD4HC__HRS__HRS16__WRCMD1_DLY_SHIFT                                   4U
#define SD4HC__HRS__HRS16__WRCMD1_DLY_WIDTH                                   4U
#define SD4HC__HRS__HRS16__WRDATA0_DLY_MASK                          0x00000F00U
#define SD4HC__HRS__HRS16__WRDATA0_DLY_SHIFT                                  8U
#define SD4HC__HRS__HRS16__WRDATA0_DLY_WIDTH                                  4U
#define SD4HC__HRS__HRS16__WRDATA1_DLY_MASK                          0x0000F000U
#define SD4HC__HRS__HRS16__WRDATA1_DLY_SHIFT                                 12U
#define SD4HC__HRS__HRS16__WRDATA1_DLY_WIDTH                                  4U
#define SD4HC__HRS__HRS16__WRCMD0_SDCLK_DLY_MASK                     0x000F0000U
#define SD4HC__HRS__HRS16__WRCMD0_SDCLK_DLY_SHIFT                            16U
#define SD4HC__HRS__HRS16__WRCMD0_SDCLK_DLY_WIDTH                             4U
#define SD4HC__HRS__HRS16__WRCMD1_SDCLK_DLY_MASK                     0x00F00000U
#define SD4HC__HRS__HRS16__WRCMD1_SDCLK_DLY_SHIFT                            20U
#define SD4HC__HRS__HRS16__WRCMD1_SDCLK_DLY_WIDTH                             4U
#define SD4HC__HRS__HRS16__WRDATA0_SDCLK_DLY_MASK                    0x0F000000U
#define SD4HC__HRS__HRS16__WRDATA0_SDCLK_DLY_SHIFT                           24U
#define SD4HC__HRS__HRS16__WRDATA0_SDCLK_DLY_WIDTH                            4U
#define SD4HC__HRS__HRS16__WRDATA1_SDCLK_DLY_MASK                    0xF0000000U
#define SD4HC__HRS__HRS16__WRDATA1_SDCLK_DLY_SHIFT                           28U
#define SD4HC__HRS__HRS16__WRDATA1_SDCLK_DLY_WIDTH                            4U

#define SD4HC__HRS__HRS29_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS29_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS29__SDMAGICNUM_MASK                           0xFFFFFFFFU
#define SD4HC__HRS__HRS29__SDMAGICNUM_SHIFT                                   0U
#define SD4HC__HRS__HRS29__SDMAGICNUM_WIDTH                                  32U

#define SD4HC__HRS__HRS30_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS30_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS30__CQSUP_MASK                                0x00000001U
#define SD4HC__HRS__HRS30__CQSUP_SHIFT                                        0U
#define SD4HC__HRS__HRS30__CQSUP_WIDTH                                        1U
#define SD4HC__HRS__HRS30__CQSUP_WOCLR                                        0U
#define SD4HC__HRS__HRS30__CQSUP_WOSET                                        0U
#define SD4HC__HRS__HRS30__HS400ESSUP_MASK                           0x00000002U
#define SD4HC__HRS__HRS30__HS400ESSUP_SHIFT                                   1U
#define SD4HC__HRS__HRS30__HS400ESSUP_WIDTH                                   1U
#define SD4HC__HRS__HRS30__HS400ESSUP_WOCLR                                   0U
#define SD4HC__HRS__HRS30__HS400ESSUP_WOSET                                   0U
#define SD4HC__HRS__HRS30__RSVD_0_MASK                               0xFFFFFFFCU
#define SD4HC__HRS__HRS30__RSVD_0_SHIFT                                       2U
#define SD4HC__HRS__HRS30__RSVD_0_WIDTH                                      30U

#define SD4HC__HRS__HRS31_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS31_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS31__HOSTFIXVER_MASK                           0x000000FFU
#define SD4HC__HRS__HRS31__HOSTFIXVER_SHIFT                                   0U
#define SD4HC__HRS__HRS31__HOSTFIXVER_WIDTH                                   8U
#define SD4HC__HRS__HRS31__RSVD_0_MASK                               0x0000FF00U
#define SD4HC__HRS__HRS31__RSVD_0_SHIFT                                       8U
#define SD4HC__HRS__HRS31__RSVD_0_WIDTH                                       8U
#define SD4HC__HRS__HRS31__HOSTCTRLVER_MASK                          0x0FFF0000U
#define SD4HC__HRS__HRS31__HOSTCTRLVER_SHIFT                                 16U
#define SD4HC__HRS__HRS31__HOSTCTRLVER_WIDTH                                 12U
#define SD4HC__HRS__HRS31__RSVD_1_MASK                               0xF0000000U
#define SD4HC__HRS__HRS31__RSVD_1_SHIFT                                      28U
#define SD4HC__HRS__HRS31__RSVD_1_WIDTH                                       4U

#define SD4HC__HRS__HRS32_READ_MASK                                  0x8000FFFFU
#define SD4HC__HRS__HRS32_WRITE_MASK                                 0x8000FFFFU
#define SD4HC__HRS__HRS32__DATA_MASK                                 0x0000FFFFU
#define SD4HC__HRS__HRS32__DATA_SHIFT                                         0U
#define SD4HC__HRS__HRS32__DATA_WIDTH                                        16U
#define SD4HC__HRS__HRS32__ADDR_MASK                                 0x7FFF0000U
#define SD4HC__HRS__HRS32__ADDR_SHIFT                                        16U
#define SD4HC__HRS__HRS32__ADDR_WIDTH                                        15U
#define SD4HC__HRS__HRS32__LOAD_MASK                                 0x80000000U
#define SD4HC__HRS__HRS32__LOAD_SHIFT                                        31U
#define SD4HC__HRS__HRS32__LOAD_WIDTH                                         1U
#define SD4HC__HRS__HRS32__LOAD_WOCLR                                         0U
#define SD4HC__HRS__HRS32__LOAD_WOSET                                         0U

#define SD4HC__HRS__HRS33_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS33_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS33__STAT0_MASK                                0xFFFFFFFFU
#define SD4HC__HRS__HRS33__STAT0_SHIFT                                        0U
#define SD4HC__HRS__HRS33__STAT0_WIDTH                                       32U

#define SD4HC__HRS__HRS34_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS34_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS34__STAT1_MASK                                0x000000FFU
#define SD4HC__HRS__HRS34__STAT1_SHIFT                                        0U
#define SD4HC__HRS__HRS34__STAT1_WIDTH                                        8U
#define SD4HC__HRS__HRS34__RSVD_0_MASK                               0xFFFFFF00U
#define SD4HC__HRS__HRS34__RSVD_0_SHIFT                                       8U
#define SD4HC__HRS__HRS34__RSVD_0_WIDTH                                      24U

#define SD4HC__HRS__HRS36_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS36_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS36__BOOT_ACT_MASK                             0x00000001U
#define SD4HC__HRS__HRS36__BOOT_ACT_SHIFT                                     0U
#define SD4HC__HRS__HRS36__BOOT_ACT_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_ACT_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_ACT_WOSET                                     0U
#define SD4HC__HRS__HRS36__BOOT_EAT_MASK                             0x00000002U
#define SD4HC__HRS__HRS36__BOOT_EAT_SHIFT                                     1U
#define SD4HC__HRS__HRS36__BOOT_EAT_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_EAT_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_EAT_WOSET                                     0U
#define SD4HC__HRS__HRS36__BOOT_EAI_MASK                             0x00000004U
#define SD4HC__HRS__HRS36__BOOT_EAI_SHIFT                                     2U
#define SD4HC__HRS__HRS36__BOOT_EAI_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_EAI_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_EAI_WOSET                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDT_MASK                             0x00000008U
#define SD4HC__HRS__HRS36__BOOT_EDT_SHIFT                                     3U
#define SD4HC__HRS__HRS36__BOOT_EDT_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_EDT_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDT_WOSET                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDC_MASK                             0x00000010U
#define SD4HC__HRS__HRS36__BOOT_EDC_SHIFT                                     4U
#define SD4HC__HRS__HRS36__BOOT_EDC_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_EDC_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDC_WOSET                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDE_MASK                             0x00000020U
#define SD4HC__HRS__HRS36__BOOT_EDE_SHIFT                                     5U
#define SD4HC__HRS__HRS36__BOOT_EDE_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_EDE_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDE_WOSET                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDM_MASK                             0x00000040U
#define SD4HC__HRS__HRS36__BOOT_EDM_SHIFT                                     6U
#define SD4HC__HRS__HRS36__BOOT_EDM_WIDTH                                     1U
#define SD4HC__HRS__HRS36__BOOT_EDM_WOCLR                                     0U
#define SD4HC__HRS__HRS36__BOOT_EDM_WOSET                                     0U
#define SD4HC__HRS__HRS36__RSVD_0_MASK                               0xFFFFFF80U
#define SD4HC__HRS__HRS36__RSVD_0_SHIFT                                       7U
#define SD4HC__HRS__HRS36__RSVD_0_WIDTH                                      25U

#define SD4HC__HRS__HRS40_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS40_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS40__BASE_ADDR0_MASK                           0xFFFFFFFFU
#define SD4HC__HRS__HRS40__BASE_ADDR0_SHIFT                                   0U
#define SD4HC__HRS__HRS40__BASE_ADDR0_WIDTH                                  32U

#define SD4HC__HRS__HRS41_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS41_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS41__BASE_ADDR1_MASK                           0xFFFFFFFFU
#define SD4HC__HRS__HRS41__BASE_ADDR1_SHIFT                                   0U
#define SD4HC__HRS__HRS41__BASE_ADDR1_WIDTH                                  32U

#define SD4HC__HRS__HRS42_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS42_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS42__DESCMECH_EN_MASK                          0x00000001U
#define SD4HC__HRS__HRS42__DESCMECH_EN_SHIFT                                  0U
#define SD4HC__HRS__HRS42__DESCMECH_EN_WIDTH                                  1U
#define SD4HC__HRS__HRS42__DESCMECH_EN_WOCLR                                  0U
#define SD4HC__HRS__HRS42__DESCMECH_EN_WOSET                                  0U
#define SD4HC__HRS__HRS42__DESCMECH_TM_MASK                          0x0000001EU
#define SD4HC__HRS__HRS42__DESCMECH_TM_SHIFT                                  1U
#define SD4HC__HRS__HRS42__DESCMECH_TM_WIDTH                                  4U
#define SD4HC__HRS__HRS42__RSVD_0_MASK                               0xFFFFFFE0U
#define SD4HC__HRS__HRS42__RSVD_0_SHIFT                                       5U
#define SD4HC__HRS__HRS42__RSVD_0_WIDTH                                      27U

#define SD4HC__HRS__HRS43_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__HRS__HRS43_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__HRS__HRS43__ERROR_ST_MASK                             0x00000001U
#define SD4HC__HRS__HRS43__ERROR_ST_SHIFT                                     0U
#define SD4HC__HRS__HRS43__ERROR_ST_WIDTH                                     1U
#define SD4HC__HRS__HRS43__ERROR_ST_WOCLR                                     0U
#define SD4HC__HRS__HRS43__ERROR_ST_WOSET                                     0U
#define SD4HC__HRS__HRS43__ERROR_VAL_MASK                            0x0000000EU
#define SD4HC__HRS__HRS43__ERROR_VAL_SHIFT                                    1U
#define SD4HC__HRS__HRS43__ERROR_VAL_WIDTH                                    3U
#define SD4HC__HRS__HRS43__RSVD_0_MASK                               0xFFFFFFF0U
#define SD4HC__HRS__HRS43__RSVD_0_SHIFT                                       4U
#define SD4HC__HRS__HRS43__RSVD_0_WIDTH                                      28U

#endif /* REG_SD4HC_HRS_MACROS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names, DRV-4756" */
/* parasoft-end-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names, DRV-4756" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits, DRV-4754" */

