/* parasoft-begin-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names, DRV-4756" */
/* parasoft-begin-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names, DRV-4756" */

/******************************************************************************
*
* (C) 2023 Cadence Design Systems, Inc. 
*
******************************************************************************
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its
*    contributors may be used to endorse or promote products derived from
*    this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
******************************************************************************
*

 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_SD4HC_CRS_MACROS_H_
#define REG_SD4HC_CRS_MACROS_H_

#define SD4HC__CRS__CRS63_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__CRS__CRS63_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__CRS__CRS63__ISES_MASK                                 0x00000001U
#define SD4HC__CRS__CRS63__ISES_SHIFT                                         0U
#define SD4HC__CRS__CRS63__ISES_WIDTH                                         1U
#define SD4HC__CRS__CRS63__ISES_WOCLR                                         0U
#define SD4HC__CRS__CRS63__ISES_WOSET                                         0U
#define SD4HC__CRS__CRS63__RSVD_0_MASK                               0x0000FFFEU
#define SD4HC__CRS__CRS63__RSVD_0_SHIFT                                       1U
#define SD4HC__CRS__CRS63__RSVD_0_WIDTH                                      15U
#define SD4HC__CRS__CRS63__SVN_MASK                                  0x00FF0000U
#define SD4HC__CRS__CRS63__SVN_SHIFT                                         16U
#define SD4HC__CRS__CRS63__SVN_WIDTH                                          8U
#define SD4HC__CRS__CRS63__RSVD_1_MASK                               0xFF000000U
#define SD4HC__CRS__CRS63__RSVD_1_SHIFT                                      24U
#define SD4HC__CRS__CRS63__RSVD_1_WIDTH                                       8U

#endif /* REG_SD4HC_CRS_MACROS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names, DRV-4756" */
/* parasoft-end-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names, DRV-4756" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits, DRV-4754" */

