/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/******************************************************************************
*
* (C) 2023 Cadence Design Systems, Inc. 
*
******************************************************************************
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its
*    contributors may be used to endorse or promote products derived from
*    this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
******************************************************************************
*

 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_SRS_H_
#define REG_SRS_H_

#include <cps_drv.h>

#include "sd4hc_srs_macros.h"

typedef struct __attribute__((packed)) SD4HC_Srs_s {
        volatile uint32_t SRS00;
        volatile uint32_t SRS01;
        volatile uint32_t SRS02;
        volatile uint32_t SRS03;
        volatile uint32_t SRS04;
        volatile uint32_t SRS05;
        volatile uint32_t SRS06;
        volatile uint32_t SRS07;
        volatile uint32_t SRS08;
        volatile uint32_t SRS09;
        volatile uint32_t SRS10;
        volatile uint32_t SRS11;
        volatile uint32_t SRS12;
        volatile uint32_t SRS13;
        volatile uint32_t SRS14;
        volatile uint32_t SRS15;
        volatile uint32_t SRS16;
        volatile uint32_t SRS17;
        volatile uint32_t SRS18;
        volatile uint32_t SRS19;
        volatile uint32_t SRS20;
        volatile uint32_t SRS21;
        volatile uint32_t SRS22;
        volatile uint32_t SRS23;
        volatile uint32_t SRS24;
        volatile uint32_t SRS25;
        volatile uint32_t SRS26;
        volatile uint32_t SRS27;
        volatile char pad__0[0x8U];
        volatile uint32_t SRS30;
        volatile uint32_t SRS31;
} SD4HC_Srs;

#endif /* REG_SRS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

