/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */
/******************************************************************************
*
* (C) 2023 Cadence Design Systems, Inc. 
*
******************************************************************************
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its
*    contributors may be used to endorse or promote products derived from
*    this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
******************************************************************************
*

 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_HRS_H_
#define REG_HRS_H_

#include <cps_drv.h>

#include "sd4hc_hrs_macros.h"

typedef struct __attribute__((packed)) SD4HC_Hrs_s {
        volatile uint32_t HRS00;
        volatile uint32_t HRS01;
        volatile uint32_t HRS02;
        volatile uint32_t HRS03;
        volatile uint32_t HRS04;
        volatile uint32_t HRS05;
        volatile uint32_t HRS06;
        volatile uint32_t HRS07;
        volatile uint32_t HRS08;
        volatile uint32_t HRS09;
        volatile uint32_t HRS10;
        volatile uint32_t HRS11;
        volatile uint32_t HRS12;
        volatile uint32_t HRS13;
        volatile uint32_t HRS14;
        volatile char pad__0[0x4U];
        volatile uint32_t HRS16;
        volatile char pad__1[0x30U];
        volatile uint32_t HRS29;
        volatile uint32_t HRS30;
        volatile uint32_t HRS31;
        volatile uint32_t HRS32;
        volatile uint32_t HRS33;
        volatile uint32_t HRS34;
        volatile char pad__2[0x4U];
        volatile uint32_t HRS36;
        volatile char pad__3[0xCU];
        volatile uint32_t HRS40;
        volatile uint32_t HRS41;
        volatile uint32_t HRS42;
        volatile uint32_t HRS43;
} SD4HC_Hrs;

#endif /* REG_HRS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

