/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/******************************************************************************
*
* (C) 2023 Cadence Design Systems, Inc. 
*
******************************************************************************
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its
*    contributors may be used to endorse or promote products derived from
*    this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
******************************************************************************
*

 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_CCP_REGS_H_
#define REG_CCP_REGS_H_

#include <cps_drv.h>

#include "ccp_regs_macros.h"

typedef struct __attribute__((packed)) CCP_Regs_s {
    volatile char pad__0[0x2000U];
    volatile uint32_t phy_dq_timing_reg;
    volatile uint32_t phy_dqs_timing_reg;
    volatile uint32_t phy_gate_lpbk_ctrl_reg;
    volatile uint32_t phy_dll_master_ctrl_reg;
    volatile uint32_t phy_dll_slave_ctrl_reg;
    volatile uint32_t phy_ie_timing_reg;
    volatile uint32_t phy_obs_reg_0;
    volatile uint32_t phy_dll_obs_reg_0;
    volatile uint32_t phy_dll_obs_reg_1;
    volatile uint32_t phy_dll_obs_reg_2;
    volatile uint32_t phy_static_togg_reg;
    volatile char pad__1[0x4U];
    volatile uint32_t phy_wr_rd_deskew_cmd_reg;
    volatile uint32_t phy_wr_deskew_pd_ctrl_0_reg;
    volatile char pad__2[0x38U];
    volatile uint32_t phy_version_reg;
    volatile uint32_t phy_features_reg;
    volatile char pad__3[0x8U];
    volatile uint32_t phy_ctrl_reg;
    volatile uint32_t phy_tsel_reg;
    volatile uint32_t phy_gpio_ctrl_0;
    volatile uint32_t phy_gpio_ctrl_1;
    volatile uint32_t phy_gpio_status_0;
    volatile uint32_t phy_gpio_status_1;
} CCP_Regs;

#endif /* REG_CCP_REGS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

